security_rover/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^srac/', include('srac.urls')),
    url(r'^admin/', admin.site.urls),
]

srac/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'srac'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/srac/login'}, name='logout'),
    url(r'^checklists/(?P<location_hash>[A-Za-z0-9_]+)', views.checklist, name='checklists'),
    url(r'^session/add/(?P<location_hash>[A-Za-z0-9_]+)', views.session_add, name='session.add'),
    url(r'^session/edit/(?P<session_id>[0-9_]+)', views.session_edit, name='session.edit'),
    url(r'^session/save/(?P<session_id>[0-9_]+)', views.session_save, name='session.save'),
    url(r'^session/view/(?P<session_id>[0-9_]+)', views.session_view, name='session.view'),
]

srac/models.py
from django.contrib.auth.models import User
from django.db import models


class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    event = models.TextField()
    event_date = models.DateTimeField()
    emp_id = models.CharField(max_length=45)


class Classification(models.Model):
    classification_name = models.CharField(primary_key=True, max_length=45)
    classification_description = models.TextField()

    def __str__(self):
        return self.classification_name


class Checklist(models.Model):
    checklist_id = models.AutoField(primary_key=True)
    classification = models.ForeignKey(Classification)
    date_registered = models.DateTimeField()
    checklist_name = models.CharField(max_length=45)
    checklist_desc = models.TextField()
    registered_by = models.ForeignKey(User, related_name="registered_by")
    edited_by = models.ForeignKey(User, related_name="edited_by")
    last_edit = models.DateTimeField()

    def __str__(self):
        return self.checklist_name


class Location(models.Model):
    building = models.CharField(max_length=45)
    floor = models.CharField(max_length=45)
    area = models.CharField(max_length=45)
    location_hash = models.CharField(primary_key=True, max_length=45)

    def __str__(self):
        return "{} {} {}".format(self.building, self.floor, self.area)


class Location_Checklist(models.Model):
    location = models.ForeignKey(Location)
    checklist = models.ForeignKey(Checklist)
    priority_number = models.IntegerField(default=1)

    def __str__(self):
        return "{} {}".format(self.location, self.checklist.checklist_name)


class Session(models.Model):
    session_id = models.AutoField(primary_key=True)
    check_date = models.DateTimeField()
    check_remarks = models.TextField()
    checker = models.ForeignKey(User)
    is_session_submitted = models.IntegerField(default=0)


class Session_Checklist(models.Model):
    CONFIRMATION_VAL = (
        ('Y', 'Yes'),
        ('N', 'No'),
        ('NA', 'Not Applicable')
    )
    session_checklist_id = models.AutoField(primary_key=True)
    session = models.ForeignKey(Session)
    location_checklist = models.ForeignKey(Location_Checklist)
    confirmation = models.CharField(max_length=45, choices=CONFIRMATION_VAL, default=CONFIRMATION_VAL[2][0])
    remarks = models.TextField()

srac/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import reverse
from django.utils import timezone
from django.views import generic
from datetime import timedelta

from .models import Event
from .models import Location
from .models import Location_Checklist
from .models import Session
from .models import Session_Checklist

import srac.messages

import json
import requests

@login_required(login_url='/srac/login/')
def checklist(request, location_hash):
    # first, check if location_hash is valid
    location = get_object_or_404(Location, pk=location_hash)

    existing_session_set = Session.objects.filter(is_session_submitted=0)
    if len(existing_session_set) == 0:
        print("There are NO existing sessions")

        # check for sessions completed an hour ago
        now = timezone.now()
        one_hour_ago = now - timedelta(hours=1)
        earlier_sessions_list = Session.objects.filter(check_date__range=(one_hour_ago, now)).filter(is_session_submitted=1)

        if len(earlier_sessions_list) > 0:
            for earlier_session in earlier_sessions_list:
                print("Earlier session: {}".format(earlier_session.session_id))
                session_checklist_set = Session_Checklist.objects.filter(session=earlier_session)
                for session_checklist in session_checklist_set:
                    if session_checklist.location_checklist.location == location:
                        context = {
                            'prompt': "recent",
                            'location': location,
                            'session': earlier_session
                        }
                        return render(request, 'srac/checklist_prompt.html', context)

        return HttpResponseRedirect(
            reverse('srac:session.add', kwargs={'location_hash': location_hash})
        )
    else:
        print("There are existing sessions")
        # check if there is an existing session in the location
        for existing_session in existing_session_set:
            for session_checklist in existing_session.session_checklist_set.all():
                if session_checklist.location_checklist.location == location:
                    print("There is an existing session for {}: {}".format(location, existing_session.session_id))
                    context = {
                        'prompt': "exist",
                        'location': location,
                        'session': existing_session
                    }
                    return render(request, 'srac/checklist_prompt.html', context)


def session_add(request, location_hash):
    current_user = get_object_or_404(User, pk=request.user.id)
    location = get_object_or_404(Location, pk=location_hash)

    context = {
        'user': current_user,
        'location': location
    }

    session = Session(
        check_date=timezone.now(),
        checker=current_user
    )
    session.save()
    context['session'] = session

    event = Event(
        event=srac.messages.new_session.format(current_user.get_full_name(), str(location)),
        event_date=timezone.now(),
        emp_id=current_user.username
    )
    event.save()

    location_checklists_set = Location_Checklist.objects.filter(location=location)
    for location_checklist in location_checklists_set:
        session.session_checklist_set.create(
            session=session,
            location_checklist=location_checklist
        )

    session_checklist_set = session.session_checklist_set.all()
    context['checklist_set'] = session_checklist_set

    return render(request, 'srac/checklist.html', context)


def session_edit(request, session_id):
    current_user = get_object_or_404(User, pk=request.user.id)

    context = {
        'user': current_user,
    }

    session = Session.objects.get(pk=session_id)
    session.checker = current_user
    session.save()
    context['session'] = session

    location = get_session_location(session)
    context['location'] = location

    event = Event(
        event=srac.messages.edit_session.format(current_user.get_full_name(), str(location)),
        event_date=timezone.now(),
        emp_id=current_user.username
    )
    event.save()

    context['checklist_set'] = session.session_checklist_set.all()

    return render(request, 'srac/checklist.html', context)


def session_save(request, session_id):
    if request.method == 'POST':
        session = Session.objects.get(pk=session_id)

        # save changes
        for session_checklist in session.session_checklist_set.all():
            session_checklist.confirmation = request.POST['confirmation_' + str(session_checklist.session_checklist_id)]
            session_checklist.remarks = request.POST['remarks_' + str(session_checklist.session_checklist_id)]
            session_checklist.save()

        session.check_remarks = request.POST['session_remarks']
        session.check_date = timezone.now()
        session.is_session_submitted = 1
        session.save()

        event = Event(
            event=srac.messages.save_session.format(session.checker.get_full_name(), get_session_location(session)),
            event_date=timezone.now(),
            emp_id=session.checker.username
        )
        event.save()

        send_email_to_admins(event)

        return HttpResponseRedirect(
            reverse('srac:session.view', kwargs={'session_id': session.session_id}) + "?success=true"
        )


def send_email_to_admins(event):
    # retrieve emails of admins
    admin_set = User.objects.filter(is_staff=True)
    admin_email = []
    for admin in admin_set:
        admin_email.append(admin.email)

    url = "http://pacebu03.lrdc.lexmark.com:8080/SecurityMail/MailService.svc/mail/send"
    headers = {"Content-Type": "application/json"}
    args = {
        "AddressFrom": "noreply@lexmark.com",
        "AddressFromName": "SRAC",
        "AddressTo": admin_email,
        "Subject": "[SRAC] {} {}".format(event.event_date, event.emp_id),
        "Body": "{}".format(event.event)
    }
    response = requests.post(url, headers=headers, data=json.dumps(args))
    if response.status_code == 200:
        print("Successfully sent emails to admins (y)")
    else:
        print("Failed to send emails to admins :(")


def session_view(request, session_id):
    session = get_object_or_404(Session, pk=session_id)
    context = {
        "checklist_set": session.session_checklist_set.all(),
        "session": session,
        "location": get_session_location(session)
    }
    if "success" in request.GET:
        context["success"] = "true"

    return render(request, 'srac/checklist_view.html', context)


def get_session_location(session):
    session_checklist_set = Session_Checklist.objects.filter(session=session)
    return session_checklist_set[0].location_checklist.location


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/srac/login/'
    template_name = 'srac/index.html'
    context_object_name = 'event_set'

    def get_queryset(self):
        return Event.objects.order_by('-event_date')

srac/templates/srac/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SRAC | Security Rover Area Checklist</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

        <!-- Custom styles for this template -->
        <link href="{% static 'srac/starter-template.css' %}" rel="stylesheet">
        {% block extrastyle %}{% endblock %}
    </head>

    <body>
        {% block navbar %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="#">Security Checklist</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'srac:index' %}">Home</a>
                    </li>
                    {% if user.is_staff == 1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'srac:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock %}
        <div class="container">
        {% block container %}
            {% if user.is_authenticated %}
            <div class="col">
                <h6>
                    Welcome {{ user.get_full_name }}
                    {% if location %}
                    to {{ location }}
                    {% endif %}
                </h6>
            </div>
            {% endif %}

            {% block content %}
            {% endblock %}
        {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
</html>

srac/templates/srac/checklist.html
{% extends "srac/base.html" %}

{% block content %}
{% if checklist_set %}
<hr class="my-4">
<div class="list-group">
    <form action="{% url 'srac:session.save' session.session_id %}" method="post">
        {% csrf_token %}
        <ul class="list-group">
        {% for checklist in checklist_set %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">#{{ forloop.counter }} {{ checklist.location_checklist.checklist.checklist_name }}</h5>
                </div>
                <p class="mb-1">{{ checklist.location_checklist.checklist.checklist_desc }}</p>
                <input type="radio"
                       id="confirmation_yes_{{ checklist.session_checklist_id }}"
                       name="confirmation_{{ checklist.session_checklist_id }}"
                       value="Y" {% if checklist.confirmation == "Y" %}checked{% endif %}>
                <label for="confirmation_yes_{{ checklist.session_checklist_id }}">Yes</label>
                <input type="radio"
                       id="confirmation_no_{{ checklist.session_checklist_id }}"
                       name="confirmation_{{ checklist.session_checklist_id }}"
                       value="N" {% if checklist.confirmation == "N" %}checked{% endif %}>
                <label for="confirmation_no_{{ checklist.session_checklist_id }}">No</label>
                <input type="radio"
                       id="confirmation_na_{{ checklist.session_checklist_id }}"
                       name="confirmation_{{ checklist.session_checklist_id }}"
                       value="NA" {% if checklist.confirmation == "NA" %}checked{% endif %}>
                <label for="confirmation_na_{{ checklist.session_checklist_id }}">Not Applicable</label>
                <div class="col">
                <textarea id="remarks_{{ checklist.session_checklist_id }}"
                            class="remarks-area"
                            name="remarks_{{ checklist.session_checklist_id }}">{{ checklist.remarks }}</textarea>
                </div>
            </li>
        {% endfor %}
        </ul>
        <div class="jumbotron starter-template">
            <p class="lead">Any comments about the area?</p>
            <textarea id="session_remarks"
                      class="remarks-area"
                      name="session_remarks">{{ session.check_remarks }}</textarea>
            <input class="btn btn-success" type="submit" value="Submit" />
        </div>
    </form>
{% else %}
    <p>No checklists are available.</p>
{% endif %}
</div>
{% endblock %}

srac/templates/srac/checklist_prompt.html
{% extends "srac/base.html" %}

{% block content %}
<hr class="my-4">
<div class="starter-template">
    <h1>Whoops!</h1>
    <p class="lead">
        {% if prompt == "recent" %}
            {{ session.checker.get_full_name }} has recently checked this location.
            <br />
            Would you like to check again?
            <br />
            Press 'Yes' to check again.
            <br />
            <a class="btn btn-lg btn-primary"
                   href="{% url 'srac:session.add' location.location_hash %}"
                   role="button">Yes</a>
        {% elif prompt == 'exist' %}
            {% if session.checker == user %}
                You are
            {% else %}
                {{ session.checker.get_full_name }} is
            {% endif %}
            currently checking this location.
            <br />
            Would you like to continue the current work?
            <br />
            Press 'Yes' to continue.
            <br />
            <a class="btn btn-lg btn-primary"
                   href="{% url 'srac:session.edit' session.session_id %}"
                   role="button">Yes</a>
        {% endif %}
        <br />
        Press 'No' to view the results.
        <br />
        <a class="btn btn-lg btn-danger"
           href="{% url 'srac:session.view' session.session_id %}"
           role="button">No</a>
    </p>
</div>
{% endblock %}

srac/templates/srac/checklist_view.html
{% extends "srac/base.html" %}

{% block content %}
<hr class="my-4">
{% if success %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>You have successfully performed the security check in this area.</p>
</div>
{% endif %}
{% if checklist_set %}
<div class="list-group">
    {% for checklist in checklist_set %}
        <div class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">#{{ forloop.counter }} {{ checklist.location_checklist.checklist.checklist_name }}</h5>
                <small class="text-muted">
                    {% if checklist.confirmation == 'Y' %}
                    Yes
                    {% elif checklist.confirmation == 'N' %}
                    No
                    {% else %}
                    Not Applicable
                    {% endif %}
                </small>
            </div>
            <p class="mb-1">{{ checklist.location_checklist.checklist.checklist_desc }}</p>
            <small class="text-muted">
                Remarks:
                {% if checklist.remarks %}
                {{ checklist.remarks }}
                {% else %}
                None
                {% endif %}
            </small>
        </div>
    {% endfor %}
    <div class="jumbotron starter-template">
        <h6>General Remarks</h6>
        <p class="lead">{{ session.check_remarks }}</p>
    </div>
</div>
{% else %}
    <p>No checklists are available.</p>
{% endif %}
{% endblock %}

srac/templates/srac/index.html
{% extends "srac/base.html" %}

{% block content %}
{% if event_set %}
<hr class="my-4">
<div class="list-group">
    {% for event in event_set %}
        <div class="list-group-item list-group-item-action" style="border: none">
            <div class="d-flex w-100 justify-content-between">
                <small class="text-muted">{{ event.event_date }}</small>
            </div>
            <p class="mb-1">{{ event.event }}</p>
        </div>
    {% endfor %}
</div>
{% else %}
    <p>No recent activities.</p>
{% endif %}
{% endblock %}